###
## Configuration
###

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

url: 
baseurl: ""

# Site Content
logo: /static/img/favicon.png

# Localization
languages: ["en", "fr"]
exclude_from_localizations: ["static"]

# Assets
sass:
 sass_dir: static/stylesheets/_scss
 style: :compressed

autoprefixer:
  browsers:
    - last 5 versions
